[tools]
go = "latest"
golangci-lint = "2.5"

[tasks.build]
description = "Build the CLI"
run = "go build . -o ./dist/adapt"

[tasks.fmt]
description = "Format code"
run = "gofmt -s -w ."

[tasks."fmt:check"]
description = "Check code formatting"
run = "gofmt -s -l ."

[tasks.test]
description = "Run tests"
run = 'go test {{arg(name="path", var=true, default="./...")}}'

[tasks.test-e2e]
description = "Run tests end-to-end"
run = [
    "docker buildx build --platform=linux/amd64 --tag test --load --file ./test_data/Dockerfile .",
    "docker run --platform=linux/amd64 test",
]


[tasks.lint]
description = "Run linters"
run = "golangci-lint run"

[tasks.clean]
description = "Remove any generated files, data, and containers"
run = [
  "rm -rf ./dist",
]
